### ISSUE TITLE
same model name with baidu, what difference  or  some advantages

### ISSUE THREAD

**Issue by zkailinzhang** [thunlp/ERNIE#10]
[https://github.com/PaddlePaddle/LARK/tree/develop/ERNIE](url)

**Comment by zzy14** [comment]
It is a coincidence that both Baidu and we chose ERNIE from the television show, Sesame Street, as the model names, which follows the interesting naming habits like ELMo and BERT. Actually, the research questions and methodologies are quite different and they can't be compared directly.
