### ISSUE TITLE
kg_embed.zip

### ISSUE THREAD

**Issue by ypc-stu** [thunlp/ERNIE#11]
你好:
我下载了kg_embed.zip，解压之后发现是entity2vec.vec，是实体性向量。请问在哪里找其对应实体名称呢？谢谢，我想转为成类似于glove形式。
期待你的回复......best

**Comment by zzy14** [comment]
`entity2id.txt`里面每一行是个实体的Wikidata ID和它在`entity2vec.vec`的行数减一。举个例子，对于`Q123 0`这一行来说，它指的是Q123的向量位于`entity2vec.vec`中的第一行。具体Wikidata ID的对应你可以通过`entity_map.txt`来完成。

**Comment by ypc-stu** [comment]
@zzy14:你好
你可以提供一下entity2id.txt 和entity_map.txt这两个文件吗？我在kg_embed.zip压缩包中我并没有发现？
我在这个项目中找了许久并没有发现.....
期待你的回复！

**Comment by zzy14** [comment]
@ypc-stu 你好，这两个文件就在`kg_embed.zip`里面...要不您重新下载一下看看？

**Comment by ypc-stu** [comment]
@zzy14 
我找到了，不好意思，刚才我没有看见这两个文件，感谢你的耐心的解答，十分感谢你。
best wishes.....

**Comment by ypc-stu** [comment]
@zzy14 你好，
我发现在entity2id.txt文件中一共有5040986行，也就是5040986实体，但是entity_map.txt文件中一共有343994行，实体和ID是一一对应的，两个文件实体数量应该相同呢，我想问问是什么原因造成的呢？
期待你的回复。。。。

**Comment by zzy14** [comment]
@ypc-stu 对的，entity_map.txt里面的实体是我们实验中涉及到的部分，如果您想要获得所有实体的名称，您可以使用Wikidata官方数据来获得（如果从网页端则为https://www.wikidata.org/wiki/Qxxx ，Qxxx是实体的ID）。
