### ISSUE TITLE
BERT BASE vs. LARGE

### ISSUE THREAD

**Issue by CarstenIsert** [thunlp/ERNIE#12]
From what I see, you are using BERT BASE for ERNIE and also compare it in the paper.
What speaks against using BERT LARGE as this is significantly better. At least it would be good to have some arguments here and in the paper about this.

**Comment by zzy14** [comment]
In our paper, we try to show the effectiveness of the knowledge information. As the expensive traing cost of LARGE model, we just use BASE for research.
