### ISSUE TITLE
关于实体数量和预训练数据的问题

### ISSUE THREAD

**Issue by shuxiaobo** [thunlp/ERNIE#13]
您好：
    感谢您发布的ERNIE的代码。
    看到实体数量预训练的大概有504万条。请问下预训练语言模型是wikipedia吗？还是其他的什么数据？因为我之前看到的wikipedia貌似没有这么多Unique的单词。

**Comment by zzy14** [comment]
实体向量是使用了Wikidata这个知识图谱来训练的，我们从Wikidata中抽取了一个子图，然后使用TransE来训练这些实体的表示，这部分和语言模型没有关系。

**Comment by shuxiaobo** [comment]
thx
