### ISSUE TITLE
About pre-trained ERNIE's model file size

### ISSUE THREAD

**Issue by lexmen318** [thunlp/ERNIE#19]
Hi,

I found the size of pytorch_model.bin inside the pre-trained ERNIE's model is only about 220M, while the BERT bert-base-uncased model file is about 400M.

I know the total amount of ERNIE parameters is about 114M, while BERT base is 110M. So I  infer that ERNIE's model file should not be smaller than BERT's.

Would you pls. tell me whether I am wrong?

thx a lot!

**Comment by zzy14** [comment]
Hi,

ERNIE's parameters are saved with the fp16 format so the model size is half of BERT. You can load the model with both fp16 and fp32.

**Comment by lexmen318** [comment]
got it, thx a lot for your kind answer.
