### ISSUE TITLE
Errors when I run the .py

### ISSUE THREAD

**Issue by hanjie0** [thunlp/ERNIE#20]
07/01/2019 14:22:40 - ERROR - knowledge_bert.tokenization -   Model name 'ernie_base' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-baert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'ernie_base' was a path or url but couldn't find any fild to this path or url.

07/01/2019 14:22:41 - ERROR - knowledge_bert.modeling -   Model name 'ernie_base' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-clarge-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'ernie_base' was a path or url but couldn't find any file as this path or url.

**Comment by zzy14** [comment]
You need to specify the model path of ERNIE. (`--ernie_model $model_folder`)

**Comment by hanjie0** [comment]
Got it Thank you
