### ISSUE TITLE
调试测试的时候出现了一些问题

### ISSUE THREAD

**Issue by proszx** [thunlp/ERNIE#21]
![image](https://user-images.githubusercontent.com/29003358/60520421-ef883300-9d17-11e9-9879-4d003fc3d975.png)
烦请修改下代码。还有就是文件解压出来的时候路径不正确，请修改md
ps:是否是因为torch版本问题？

**Comment by zzy14** [comment]
我猜测是你的文件下载时损坏，导致解压出的实体向量不全，有某一实体的维度只有74。

**Comment by proszx** [comment]
行 那我试试

**Comment by proszx** [comment]
ok
