### ISSUE TITLE
What is the meaning of entity column

### ISSUE THREAD

**Issue by hanjie0** [thunlp/ERNIE#23]
in the train.csv. the typical format of an entity is 
[['Q8029103', 139, 143, 0.5], [......]]
Here 'Q8029103' is the identifier of the entity. 
what is the meaning for 139, 143, 0.5 ?

**Comment by zzy14** [comment]
The second number is the beginning of the entity mention, the third number is the end of the entity mention, and the fourth number is the score of entity linking given by the linking model.

**Comment by hanjie0** [comment]
Dear sir, may I ask you to give me more details? 
_"The second number is the beginning of the entity mention"_ 
do you mean the location of entity in the sentence, which is the the content of 'text' column. 
_"the fourth number is the score of entity linking given by the linking model."_
Which linking model ? 
Anyway, if I would like to create such a file in the format of 'train.json',  I do need the details to  make my scripts

**Comment by zzy14** [comment]
Please refer to `code/example.py` for the detail of preparation.

**Comment by hanjie0** [comment]
from the code/example.py. I think the a.begin, a.end, a.score are returned by tagme. 
But the values (a.begin, a.end, a.score) are used for the further ERNIE training and testing or not?

**Comment by hanjie0** [comment]
forgive my poor background. Again.  for a.begin, a.end, they are location of the entity in the sentence ? 
and if they are used for ERNIE training and testing?
