### ISSUE TITLE
Preparation of ernie

### ISSUE THREAD

**Issue by hanjie0** [thunlp/ERNIE#24]
If I have my own KG and labeled text. what I should do before I use Ernie to classify my text ?
how can I get the things such as 
entity2vec
?

**Comment by zzy14** [comment]
If you want to use your own KG, you need to use the knowledge embedding algorithm to learn entity2vec and pre-train Ernie on your dataset.

**Comment by hanjie0** [comment]
when I checked the example.py of ERNIE. I found that it used the "tagme" to get the entity properties such as entity 'title', 'begin', 'end', '...'. But if I use the TransE to learn the entity2vec of my own KG, how tagme can get the information of my KG. in this case, how can I inject my own KG to ERNIE?

**Comment by zzy14** [comment]
You need to use your own linking tool for your KG. For example, you can use simple string matching.
