### ISSUE TITLE
Can I invoke entities without KG embedding?

### ISSUE THREAD

**Issue by lexmen318** [thunlp/ERNIE#26]
Hi,

If I have my own KG entities (e.g. about 500 focus on specific domain), can I just invoke entities to ERNIE without KG embedding.

Maybe I would make some modification to the model, making entity sequence aligned to token sequence and adding one embedding module.

I wonder whether my solution could have the similar result as ERNIE.

Thx a lot!

**Comment by zzy14** [comment]
I think it's a reasonable solution and you can have a try.

**Comment by lexmen318** [comment]
OK
