### ISSUE TITLE
Did you consider any other knowledge embedding model, such as transH or others.

### ISSUE THREAD

**Issue by lexmen318** [thunlp/ERNIE#28]
As we know, transE can not represent complicate relation such as 1 to multiple, multiple to 1 and multiple to multiple.

thx a lot!

**Comment by zzy14** [comment]
Yes, you can replace TransE by other KE model. In this case, transE is very fast to train on our large-scale knowledge graph.

**Comment by lexmen318** [comment]
ok. thx.
