### ISSUE TITLE
[Question] Wikipedia pre-training dataset

### ISSUE THREAD

**Issue by mmarius** [thunlp/ERNIE#3]
First, thanks for releasing your code! 

Are you planning to also release the Wikipedia pretraining data and corresponding Wikidata embeddings?

**Comment by zzy14** [comment]
As the Wikipedia pretraining data is quite large, we will not release the full data. However, we will give some instructions about how to construct the training data recently. And, we have released the Wikidata embedding [here](https://drive.google.com/open?id=1IyqqBtrZ9ujy_Ew4XEoJga6Ylcs27cFy).

**Comment by ledw** [comment]
@zzy14 Thanks for releasing your model and code! I have a follow up question regarding the wikipedia pretraining data: what is the entity linking tool you used to obtain aligned data? From the example code, it seems that the TAGME API is slow. Thanks!

**Comment by zzy14** [comment]
@ledw In Wikipedia corpus,  there are human-annotated alignments from the anchors.

**Comment by ledw** [comment]
@zzy14 Thanks for your reply. That makes a lot of sense. Any chance that you could also release the code for preprocessing the wikipedia corpus?

**Comment by caoh18** [comment]
I am wondering when  we can get instructions about how to construct the training data using Wikipedia?
