### ISSUE TITLE
Questions regarding Tagme

### ISSUE THREAD

**Issue by Megavoxel01** [thunlp/ERNIE#31]
Hi!
I'm wondering how do you manage to label large corpus like Wikipedia using Tagme in short time? From my experience with Tagme API, the response time can be pretty slow when labeling a large collection of long articles and it may require days to fully annotate the Wikipedia corpus. Is there any "local" version of Tagme or am I simply missing something here? Any help would be appreciated.

Best regards

**Comment by zzy14** [comment]
Hi!

For Wikipedia, we didn't use Tagme as there are existing alignments (the hyperlinks in the documents) in the corpus. This is following the setting of [Knowledge Graph and Text Jointly Embedding](https://www.aclweb.org/anthology/D14-1167).

**Comment by Megavoxel01** [comment]
Hi!
Thanks for the reply. So how do you handle the case where most entity mentions are not linked? In most Wikipedia articles quite a few entity mentions are not linked through hyperlinks if they are not located in the opening paragraph. Do you simply discard these sentences if anchor links have a small coverage rate?

**Comment by zzy14** [comment]
Yes, just discard them.

**Comment by Megavoxel01** [comment]
Thank you! That helps a lot.
