### ISSUE TITLE
Can not find any code about "[HD] and [TL]".

### ISSUE THREAD

**Issue by lexmen318** [thunlp/ERNIE#32]
The paper says that the tokens [HD] and [TL] are used to present head entities and tail entities respectively. But I can't find any code about this.

thx. a lot!

**Comment by zzy14** [comment]
Please check the 151st line in "run_fewrel.py".

**Comment by lexmen318** [comment]
OK, actually # and $ are used instead?

**Comment by zzy14** [comment]
Yes.
