### ISSUE TITLE
关于ERNIE中\knowledge_bert\file_utils.py中的import疑问

### ISSUE THREAD

**Issue by randomtutu** [thunlp/ERNIE#33]
作者你好呀

`from typing import Optional, Tuple, Union, IO, Callable, Set`

在typing里没有这些变量或者是类？

其实我最主要的是想弄清楚，entity的token怎么和sentence的token进行对齐的。

我想在window下面试试example.py，不知道是不是系统的原因

**Comment by zzy14** [comment]
这块代码是从`pytorch_pretrained_bert`那里继承过来的，应该没有问题。你运行`example.py`报错吗，报的是什么呢？
