### ISSUE TITLE
复现tacred的finetune,准确率和论文相差很大

### ISSUE THREAD

**Issue by tuziwa** [thunlp/ERNIE#34]
您好！我尝试复现ERNIE在tacred上的fine-tuning，论文里给出的P R F1分别是69.97 66.08 67.97，但是我得到的结果是
Final Score:Precision (micro): 87.648%
                  Recall (micro): 87.642%
                  F1 (micro): 87.645%
因为我安装apex一直失败，故没有用apex,只将代码中的.half()改为.float().其他完全按照readme上的步骤进行的操作。
（1）train：python code/run_tacred.py   --do_train   --do_lower_case   --data_dir data/tacred   --ernie_model ernie_base   --max_seq_length 256   --train_batch_size 32   --learning_rate 2e-5   --num_train_epochs 4.0   --output_dir output_tacred      --loss_scale 128 --threshold 0.4
（2）eval：python code/eval_tacred.py   --do_eval   --do_lower_case   --data_dir data/tacred   --ernie_model ernie_base   --max_seq_length 256   --train_batch_size 32   --learning_rate 2e-5   --num_train_epochs 4.0   --output_dir output_tacred     --loss_scale 128 --threshold 0.4
（3）score：python code/score.py output_tacred/test_gold_model.bin.txt output_tacred/test_pred_model.bin.txt
以上是我得到结果的完整命令。
想请教一下是什么原因。

**Comment by zzy14** [comment]
我发现代码在输出标签的时候映射有些问题，现在修改完了，您再试试应该就没问题了。TACRED里的NA需要额外进行处理。
