### ISSUE TITLE
Questions about OpenEntity

### ISSUE THREAD

**Issue by antct** [thunlp/ERNIE#35]
Hi, I found your OpenEntity Dataset only remains the general labels like 'person', 'location' and so on. I try to recover all the labels with the total amount of 10331. I use 'code/run_typing' for training just modify the variable 'label_list'. It seems that other running configs don't need to change.
But the result is quite strange, the macro score can only reach (0.0003825039934902759, 0.052011114612163914, 0.0007594229822059352).
Maybe some error in my process cause this huge bias, have you experimented on the complete ultra-fine data set?
Thanks a lot~

**Comment by zzy14** [comment]
Sorry, we haven't experimented on the complete dataset because we think the data is too small to train a deep transformer model for hundreds of labels classification. According to your description, the process seems correct.

**Comment by antct** [comment]
Thanks.
