### ISSUE TITLE
About BERT

### ISSUE THREAD

**Issue by antct** [thunlp/ERNIE#36]
I try modify origin BERT SQUAD task for entity typing. For a sentence like, "left_context_token + mention_span + right_context_token', I adapt the whole context and mention_span as inputs. The input format is '[CLS] context_tokens [SEP] mention_tokens [SEP] [PAD]*'.
The network structure is just same as origin SQUAD task (BERT pooled_out + FC). I evaluate my BERT model in OpenEntity dataset and get something different from your paper.
May I know something about your BERT implementation?

**Comment by zzy14** [comment]
The input format of BERT is as same as ERNIE, which you can refer to Fig. 3 in the paper. For the entity typing task, you just need to replace ERNIE with BERT in the code.

**Comment by antct** [comment]
Thanks~
