### ISSUE TITLE
Which version of apex(commit) have you used

### ISSUE THREAD

**Issue by raghavlite** [thunlp/ERNIE#39]
Hi,
I was trying to replicate the experiments but failed to do so because of due to a version mismatch of apex. Would be grateful if you could let me know the exact commit id for this.

**Comment by zzy14** [comment]
You can try `apex==0.1`.

**Comment by DesmonDay** [comment]
I have apex==0.1 on my computer. However, when I run the code, it outputs the following error:
Traceback (most recent call last):
  File "code/run_pretrain.py", line 278, in main
    from apex.optimizers import FP16_Optimizer
ImportError: cannot import name 'FP16_Optimizer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "code/run_pretrain.py", line 421, in <module>
    main()
  File "code/run_pretrain.py", line 281, in main
    raise ImportError("Please install apex from https://www.github.com/nvidia/apex to use distributed and fp16 training.")
ImportError: Please install apex from https://www.github.com/nvidia/apex to use distributed and fp16 training.

I feel very stange. I check apex and I cannot import the FP16_Optimizer from apex.optimizers indeed. What went wrong?

**Comment by zzy14** [comment]
Sorry, I ignore the commit information. It is `880ab925bce9f817a93988b021e12db5f67f7787`.

**Comment by scuhz** [comment]
hi, i hava the same exception. how should i  do with the commit information?
