### ISSUE TITLE
Can you explain more about the pretrained files?

### ISSUE THREAD

**Issue by qianc62** [thunlp/ERNIE#40]
entity_map.txt and entity2id.txt and entity2vec.vec.
Why there is a different size between entity_map.txt (3493994) and entity2vec.vec (5040986)? So how i extract entity (word) vectors?

**Comment by zzy14** [comment]
The size of `entity_map.txt ` and `entity2vec.vec` should be the same. I guess you uncompress the file in Windows. You can try to uncompress this in the Unix-based system.

**Comment by calebjacksonhoward** [comment]
Where should I be able to find, or how should I be able to generate entity2id.txt?
