### ISSUE TITLE
Entity    question？

### ISSUE THREAD

**Issue by ypc-stu** [thunlp/ERNIE#42]
你好，
       我在做命名实体识别实验想借助你的提供的kg_embed.zip，作为一种辅助识别，
但是kg_embed.zip里面的实体没有实体的类别(比如人名、地名。组织名等)，请问一下怎么对kg_embed.zip进行分类呢？

**Comment by zzy14** [comment]
你好，我们的knowledge embedding是用作模型的输入特征，你可以重新用自己的数据训练一个新的KE，我们组也有开源工具包可以使用。([OpenKE](https://github.com/thunlp/OpenKE))
