### ISSUE TITLE
Which entities are sampled for pre-training TransE KGembedding?

### ISSUE THREAD

**Issue by izuna385** [thunlp/ERNIE#44]
Thanks for uploading code.
I have quesition about paper, 
>> we sample part of Wikidata which contains 5, 040, 986 entities and 24, 267, 796 fact triples.

Actually I previously asked [this](https://github.com/thunlp/ERNIE/issues/18), but what I'd like to know is 

1. How entities are sampled from wikidata?

2. How many entities are sampled from wikidata?

3. How wikidata's entity and wikipedia entity are aligned? 

If you'd know about these or where in codes this sampling part exists, I'd appreciate it much.
Thanks.

**Comment by zzy14** [comment]
Hi, sorry for the ambiguous description in our paper. We sampled  5,040,986 entities from Wikidata. We selected the entities appearing in our pre-training corpus and their neighbors. Wikidata provides entities' Wikipedia links, which can be used for alignments.

**Comment by izuna385** [comment]
Thanks for details. I understand how entities are sampled and aligned.
Sorry for one more question. How edges are sampled? I guess that edges whose head entity and tail one are appeared in pre-training corpus are sampled, but if this is incorrect, I'd appreciate if you'd write it.

**Comment by zzy14** [comment]
Yes, we remain the edges whose head entity and tail one appear in the pre-training corpus.

**Comment by izuna385** [comment]
I got it, Thanks!
