### ISSUE TITLE
where is ernie_base/vocab.txt?

### ISSUE THREAD

**Issue by Masterchenyong** [thunlp/ERNIE#45]
hello! where is ernie_base/vocab.txt?

**Comment by Chilydream** [comment]
Hello, did you find the file "vocab.txt"? Can you tell me where it is or how to get it?

**Comment by Riroaki** [comment]
> Hello, did you find the file "vocab.txt"? Can you tell me where it is or how to get it?

Hello, I met same problem and I found the vocab.txt int the model directory which you should download before running the code: https://drive.google.com/file/d/1m673-YB-4j1ISNDlk5oZjpPF2El7vn6f/view
