### ISSUE TITLE
Share the triples used to train knowledge embeddings

### ISSUE THREAD

**Issue by zhiyangxu-VT** [thunlp/ERNIE#48]
HI, thanks to this great work.

I read previous issue that you sampled from the original Wikidata knowledge graph and use this subgraph to train TransE. Can you share the subgraph used to train the knowledge embeddings? I want to train the knowledge embedding myself. Thank you.

**Comment by zzy14** [comment]
Hi, here is the [link](https://www.dropbox.com/s/cv67ssqzl73cjq9/wiki_graph.tar.gz?dl=0) to the training graph. In `train2id.txt`, each line consists of head, tail, and relation.

**Comment by zhiyangxu-VT** [comment]
Dear Zhang,

Thanks for sharing this training graph. It helps a lot.

Sincerely,
Zhiyang Xu
