### ISSUE TITLE
Why not add relation classification into pretrained task? 

### ISSUE THREAD

**Issue by HaishuoFang** [thunlp/ERNIE#5]
Thanks for your code. Why not add relation classification during pretraining?
 And do u consider multi-relation in one sentence? In most cases, one sentence could contain multi-relationships between different entities. Because I see that your example in your paper is two entity relationship.

**Comment by zzy14** [comment]
Thanks for your question. Relation classification is a good task to introduce external knowledge while we don't have a large-scale relation classification dataset for pre-training.
