### ISSUE TITLE
Source code TACRED F1 score doesn't correspond with the F1 score in the paper

### ISSUE THREAD

**Issue by 106753004** [thunlp/ERNIE#52]
Hello,
I fine-tuned ERNIE on TACRED for the relation classification task. I got the ERNIE F1 score at 66.xx which doesn't correspond with the F1 score 67.97 in the ERNIE paper. 
I followed the same instructions and the same parameters as you mentioned on Github. There's no problem with FewRel and Figer but I obtained the poorer score on OpenEntity and TACRED, especially TACRED.   
Could you please give me the parameters you used in the ERNIE paper on OpenEntity and TACRED? I wanna obtain the same results as your paper mentioned.

**Comment by zzy14** [comment]
Sorry for missing the detail when reorganizing the code. For TACRED, I set `--warmup_proportion 0` and `bias_correction=False` for `FusedAdam` (Line 573 in `run_tacred.py`). 

Can you share your result on OpenEntity? The parameters work on my machine.

**Comment by 106753004** [comment]
OpenEntity   f1: 74.8%. I used the same parameters
After I add --warmup_proportion 0 and bias_correction=False for FusedAdam (Line 573 in run_tacred.py), it becomes pooer. I obtain 74.12% f1 score.

Could you please upload the new parameters you used?

**Comment by yushengsu-thu** [comment]
@106753004 
I try to change the optimizer to AdamW and use the parameters as below:
python3 code/run_tacred_new.py \
    --do_train \
    --do_eval \
    --data_dir data/tacred \
    --model ernie_base \
    --train_batch_size 32 \
    --learning_rate 2e-5 \
    --num_train_epochs 4 \
    --max_seq_length 256 \
    --do_lower_case \
    --output_dir output_tacred_new \
    --loss_scale 128 \
    --threshold 0.4
Then, I can obtain the approximate results on TACRED in the paper.

As for Open Entity, you can get the approximate results by replacing the train_batch_size 32 with the train_batch_size 16.

**Comment by zzy14** [comment]
The code and README.md have been updated.
