### ISSUE TITLE
[bug] some small fix for extract.py

### ISSUE THREAD

**Issue by Riroaki** [thunlp/ERNIE#54]
Hi, thanks for your great work, however I met some bugs when executing the `pretrain_data/extract.py` script:
1. related to a bug with the python library `bs4`, the soup parser should be initialized by `features="html.parser"` instead of `features="html5lib"`: https://github.com/coursera-dl/edx-dl/issues/434
2. in the lookup step, `doc.find_all("a")` might be NoneType and will raise uncaught exception.

The multiproccessing might exit silently if exception occurs...at least that's what happened on my device.

**Comment by Riroaki** [comment]
Hi I just made a PR https://github.com/thunlp/ERNIE/pull/55

**Comment by zzy14** [comment]
Thanks!
