### ISSUE TITLE
Evaluation on TACRED should remove "NA" token

### ISSUE THREAD

**Issue by Riroaki** [thunlp/ERNIE#56]
In the evaluation / test part, the metrics should take special care of "NA" token as the data consists of over 80% percent of this token, and ignorant of it would lead to over-estimation of model.

And more metrics like f1, recall should be added, according to the metrics in OpenNRE:
https://github.com/thunlp/OpenNRE/blob/c7e4f81d2b55febc3fc6b365de277d97ed60608a/opennre/framework/data_loader.py#L53

I'll make a pr later.

**Comment by zzy14** [comment]
Thanks. In fact, I add an extra script `code/score.py` from the repo of TACRED for the evaluation.
