### ISSUE TITLE
Confusing the Part of ''Prepare Pre-train Data'' in Readme.

### ISSUE THREAD

**Issue by scuhz** [thunlp/ERNIE#58]
python3 code/run_pretrain.py --do_train --data_dir pretrain_data/merge --bert_model ernie_base --output_dir pretrain_out/ --task_name pretrain --fp16 --max_seq_length 256
I think the value of the '--bert_model' is 'bert_base_uncased' rather 'ernie_base'?

**Comment by leezy233** [comment]
i am also confused, so what is the final conclusion?

**Comment by leileilin** [comment]
> python3 code/run_pretrain.py --do_train --data_dir pretrain_data/merge --bert_model ernie_base --output_dir pretrain_out/ --task_name pretrain --fp16 --max_seq_length 256 I think the value of the '--bert_model' is 'bert_base_uncased' rather 'ernie_base'?

so is ernie_base or bert_base_uncased?
