### ISSUE TITLE
unable to download kg_embed.tar.gz

### ISSUE THREAD

**Issue by huiyusun** [thunlp/ERNIE#59]
Hi, 

I am having trouble finishing the download of the kg_embed.tar.gz file. Everytime when the download gets to around 400MB, it fails and restarts. So the file never finishes downloading. I have tried downloading using Google Chrome and Safari but neither works.

Could you advise on what the issue might be, or is there a alternative way to download the file?

Best,

Huiyu

**Comment by zzy14** [comment]
Which source did you use? If you are in China, we recommend Tsinghua Cloud. If not, we recommend Google Drive.

**Comment by huiyusun** [comment]
My bad, for some reason I missed the Google Drive link. Now it's downloading just fine. Thanks :)
