### ISSUE TITLE
预训练数据的问题

### ISSUE THREAD

**Issue by woocoder** [thunlp/ERNIE#60]
发现在准备预训练数据的时候，'code/merge.py'会读取'pretrain_data/data/'文件夹下的数据，但readme中并没有看到相关的数据集公布，请问是没有公开吗？

**Comment by zzy14** [comment]
数据是用的英文维基语料，按[这里](https://github.com/thunlp/ERNIE#prepare-pre-train-data)的步骤可以完成数据处理，`merge.py`是中间一步。

**Comment by woocoder** [comment]
> 数据是用的英文维基语料，按[这里](https://github.com/thunlp/ERNIE#prepare-pre-train-data)的步骤可以完成数据处理，`merge.py`是中间一步。

多谢回复，发现问题了，之前是因为nltk没装，但python多线程没有报错信息，所以没有生成预训练数据。
