### ISSUE TITLE
Query regarding the system specification

### ISSUE THREAD

**Issue by nikit-srivastava** [thunlp/ERNIE#64]
Hi,
I have been trying to pre-train ERNIE using the sample data provided in the repository. However, I keep running out of the GPU (nvidia-2080ti) memory. I tried looking for the system specification used by the authors to pre-train, but couldn't find it being mentioned in the paper or the repository. It would be nice if you could provide some input on the number of GPUs and time you spent to pre-train your model using the configuration mentioned in the readme file.

**Comment by zzy14** [comment]
Thanks for your question! We used 8 2080Ti for nearly one day to pre-train our model.

**Comment by nikit-srivastava** [comment]
@zzy14 Thank you for providing the information. That would help me a lot :)
