### ISSUE TITLE
Different shape embedding

### ISSUE THREAD

**Issue by nikit-srivastava** [thunlp/ERNIE#67]
Hello,
I have been trying to configure your model for pretraining on different datasets. I have managed to modify the data processing part to deal with custom data. However, when it comes to embeddings, I have a pre-trained one with 200 dimensions. The pretrain code in your repository only works with embeddings of 100 dimensions. 

Could you please provide some input on how/where can I modify the code to deal with embeddings of different shapes?

**Comment by zzy14** [comment]
Hi,

Sorry for the late reply. You could directly change the `100` to `200` in this repo. I have roughly checked the code and list the lines containing `100`.

- `code/eval_tacred.py` Line 468
- `code/example.py` Line 89
- `code/eval_fewrel.py` Line 423
- `code/eval_typing.py` Line 443
- `code/eval_figer.py` Line 443
- `code/run_tacred.py` Line 503
- `code/run_pretrain.py` Line 178
- `code/knowledge_bert/modeling.py` Line 277 & 306
- `code/run_typing.py` Line 498
- `code/run_fewrel.py` Line 480

**Comment by nikit-srivastava** [comment]
Thank you for your response :)
