### ISSUE TITLE
FewRel task weights not initialized from pretrained model

### ISSUE THREAD

**Issue by nikit-srivastava** [thunlp/ERNIE#68]
Hello,
I am trying to fine-tune the pre-trained model on FewRel data. I am getting the following message in the logs:

`INFO - knowledge_bert.modeling -   Weights of BertForSequenceClassification not initialized from pretrained model: ['classifier.weight', 'classifier.bias']`

`INFO - knowledge_bert.modeling -   Weights from pretrained model not used in BertForSequenceClassification: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.predictions_ent.transform.dense.weight', 'cls.predictions_ent.transform.dense.bias', 'cls.predictions_ent.transform.LayerNorm.weight', 'cls.predictions_ent.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias']`

The program then continues with the training, however, I would like to know if this is expected behavior. 

I suspect that this is because I have updated some part of the code in pretrain script to accommodate the updates in nvidia's apex library.

Let me know your thoughts on this.

**Comment by zzy14** [comment]
Hi,

It's expected behavior. The parameter of `classifier` is initialized before fine-tuning and is not pre-trained. The parameter of `cls` is for the prediction of language modeling and is not used during fine-tuning.
