### ISSUE TITLE
KG中的实体信息融入到LM中的疑问

### ISSUE THREAD

**Issue by kunpeng199494** [thunlp/ERNIE#69]
在T-ENCODER中，编码的信息是一个个BPE后的sub_token；在K-ENCODER中，编码的实体信息是一个个整体词汇，肯定不是sub_token，那么如何选择对应关系呢？
假设：
1.属于实体的每个sub_token都进行mask
2.只选择属于实体的first_sub_token
我看到原始论文里面的是上述第二种假设
请问：
1.你们是按照第二种假设做的吗？
2.有没有对比过第一种假设情况？

**Comment by zzy14** [comment]
您好，

感谢您的问题！我们尝试过这两种做法，发现效果差不多，但是第二种简单一些所以我们选了第二种。
