### ISSUE TITLE
TAGME的authorization token要如何获得

### ISSUE THREAD

**Issue by gaozhiguang** [thunlp/ERNIE#72]
您好，我在d4science “https://services.d4science.org/group/tagme/”注册了之后，出现了这个页面：
![image](https://user-images.githubusercontent.com/34132216/113980674-5afe1d80-9879-11eb-99cb-e699909a287e.png)
我找不到授权码在哪，您能告诉我要在哪里找到吗？谢谢！

**Comment by ZoeYou** [comment]
可以尝试下这个链接：
[(https://sobigdata.d4science.org/home)](https://sobigdata.d4science.org/home)

登陆后选择Applications中的TagMe，在网页左下角会显示personal token的信息

**Comment by gaozhiguang** [comment]
谢谢你的建议，我已经找到了授权码，谢谢！ @ZoeYou

**Comment by LuoBTong** [comment]
您好，我尝试了(https://sobigdata.d4science.org/home)这个链接，用gmail登录，只出现这个页面
![image](https://github.com/thunlp/ERNIE/assets/118579278/94c00ae5-574b-4a5d-8a0a-45637760b196)
显示服务器错误
