### ISSUE TITLE
when using the model provided here(ernie_base) with multiple gpus, something wrong.

### ISSUE THREAD

**Issue by gaozhiguang** [thunlp/ERNIE#74]
Hi, when i use the model(ernie_base) provided here for training with multiple GPU, i met some problem. In detail, i replace the original bert-base-uncased with the ernie-base, i find this issue.
![image](https://user-images.githubusercontent.com/34132216/114885566-5a492680-9e39-11eb-829a-63c7ad856758.png)
as you can see, i use the gpu 5,7 , but the process running on the 7th gpu occupy a lot of memory on the 5th gpu, and the original bert didn't have this problem, so i pretty sure that it is your model provided here having some problem or the code you provided here having some probelm, can you take a look, or have you met the same problem?

**Comment by zzy14** [comment]
Sorry for the delayed response. Could you please provide more details, such as batch size and GPU number?

**Comment by gaozhiguang** [comment]
Hi, the batch size is 140, the GPU number is 5,7, GPU: 2080Ti, 11G.

**Comment by zzy14** [comment]
It seems that GPU-5 is out of memory (10111+777 is close to 11G).
