### ISSUE TITLE
关于TAGME实体抽取

### ISSUE THREAD

**Issue by ZZAster** [thunlp/ERNIE#76]
我最近正在尝试用ERNIE在一些数据集较大的任务上微调（例如SQUAD）

遇到一个问题是在使用tagme抽取文本中的实体时，速度非常慢（处理一个句子通常需要4s以上），而且中途会出现网络请求超时导致实体抽取失败的情况。

请问你们在一些较大的数据集上微调时（例如GLUE的QQP、MNLI）是如何解决这一网络问题的呢？

**Comment by yiyaxiaozhi** [comment]
我也遇到了这个问题，请问有什么好的方法可以解决吗?换一个实体识别工具不知道是否可行？

**Comment by zzy14** [comment]
我们做的时候是配置了一个本地的tagme，可以参考这个[repo](https://github.com/gammaliu/tagme)。我们没试过别的工具，可能也是一个方案。
