### ISSUE TITLE
tried run_tacred.py, but training progress stuck at 0% for three days

### ISSUE THREAD

**Issue by Coopercoppers** [thunlp/ERNIE#77]
Hi, I tried to finetune the model for tacred, and i used the code python3 code/run_tacred.py   --do_train   --do_lower_case   --data_dir data/tacred   --ernie_model ernie_base   --max_seq_length 256   --train_batch_size 32   --learning_rate 2e-5   --num_train_epochs 4.0   --output_dir output_tacred   --fp16   --loss_scale 128 --threshold 0.4.   However,  the interface says that the progress stuck at 0% for three days,  
![QQ截图20210711235241](https://user-images.githubusercontent.com/59197421/125201794-1f715600-e2a3-11eb-85bc-15e095131bbf.png). I am at loss about what to do? Any suggestions?

**Comment by zzy14** [comment]
Maybe your server has run out of memory. Did you try other tasks?
