### ISSUE TITLE
Questions about model inputs and model layers

### ISSUE THREAD

**Issue by light8lee** [thunlp/ERNIE#8]
Thank you for releasing this wonderful work.
What confused me are:
1. According to your model, if there is a entity contains more than one tokens, for example `jim henson`, the information fusion is only done at the first token, that is `jim`, is it better than doing information fusion both at `jim` and `henson`?
2. I draw three figures of your model layers(sim, mix and norm):
![image](https://user-images.githubusercontent.com/13532435/58460003-40c46600-815f-11e9-9afa-b3bb46a23221.png)
![image](https://user-images.githubusercontent.com/13532435/58460028-4d48be80-815f-11e9-804d-278ec0ebd052.png)
![image](https://user-images.githubusercontent.com/13532435/58460042-55a0f980-815f-11e9-93c2-f4d873da1479.png)
it seems that the information fusion appears before multihead attentions of entities(mix layer), which is different from your aggregator in Figure 2.
3. I'm a little confused about the alignment  in Figure 3, I didn't read this part of codes, what is the value of `placeholder`, an all zeros vecotr or an embedding vector learning from trainings?

**Comment by zzy14** [comment]
1. I think there are some strategies for information fusion. And, we assume the attention mechanism can help the message passing between the tokens in the entity mention so we just choose the first token in the entity mention.
2. Yes, we use information fusion before multi-head attentions of entities to introduce position information into the entity embeddings.
3. The input doesn't contain `placeholder`, which is used for a neat looking.

**Comment by light8lee** [comment]
Thank you for your reply, it's really helpful.
