### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by leileilin** [thunlp/ERNIE#83]
你好，
得知你的结果是在预训练好的bert上微调，为什么readme上预训练的命令的--model-name却是 ernie_base？
非常感谢！！

**Comment by zzy14** [comment]
模型是使用预训练好的bert来进行初始化，引入了新的知识网络后做了进一步的预训练，训练完的模型是ernie_base。

**Comment by leileilin** [comment]
> 模型是使用预训练好的bert来进行初始化，引入了新的知识网络后做了进一步的预训练，训练完的模型是ernie_base。

可是你的预训练命令的model_name参数是ernie_base

**Comment by zzy14** [comment]
噢噢，确实，我们预训练的时候重命名了bert_base为ernie_base。严谨来说确实是ernie_base。感谢您指出这个问题！
