### ISSUE TITLE
bermodel应用

### ISSUE THREAD

**Issue by Hou-jing** [thunlp/ERNIE#84]
你好，在使用预训练模型生成词向量时，input是什么参数呢？
我使用了以下数据测试，但是显示错误（能否提供一个使用BertModel的example呢？）
model, _=BertModel.from_pretrained(args.ernie_model)
inputs_id=torch.tensor([[ 101, 2207, 5273,  109,  791, 1921,  109,  102],
        [ 101, 3616, 3152,  109,  809,  711,  109,  102],
        [ 101, 2207, 5273,  108, 1762,  108, 1408,  102]])
att_mask=torch.tensor([[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1]],dtype=torch.long)

token_type_id=att_mask
input_ent=att_mask
ents_mask=att_mask
# , token_type_ids=None, attention_mask=None, input_ent=None, ent_mask=None
output = model(input_ids=inputs_id,input_ent=input_ent,ent_mask=ents_mask)

![image](https://user-images.githubusercontent.com/75936962/153614180-a8021dbc-9c27-447a-aa84-222c5efa39e4.png)

**Comment by zzy14** [comment]
您好，可以参考这个[代码](https://github.com/thunlp/ERNIE/blob/master/code/example.py)。

**Comment by Hou-jing** [comment]
你好，在example的代码中BertModel类并没有被使用，
当我尝试输入tokens_tensor, ents_tensor, ent_mask, segments_tensors这四个参数时，BertModel调用仍然显示错误。
请问，在ERNIE中的BertModel的使用和bert本身的BertModel的用法和输入参数相同吗？

**Comment by zzy14** [comment]
ERNIE中的BertModel和BERT本身的输入参数是不相同的，有额外的entity id和entity mask作为输入参数。
