### ISSUE TITLE
anchor2id.txt您访问的页面不存在

### ISSUE THREAD

**Issue by estarpro** [thunlp/ERNIE#85]
你好，当我准备Pre-train Data然后执行第二条命令时 wget -c https://cloud.tsinghua.edu.cn/f/1c956ed796cb4d788646/?dl=1 -O anchor2id.txt时，返回的是404 page not found，请问是把这个文件取消掉了吗？

**Comment by h-peng17** [comment]
你好，原有的网盘链接已经失效，新的网盘链接为：https://cloud.tsinghua.edu.cn/f/6318808dded94818b3a1/?dl=1

**Comment by estarpro** [comment]
好的，感谢回复~
