### ISSUE TITLE
Prepare Pre-train Data

### ISSUE THREAD

**Issue by zzg-971030** [thunlp/ERNIE#86]
您好，请问可以开源Wikidata4 的三元组文件吗

**Comment by zzy14** [comment]
https://cloud.tsinghua.edu.cn/d/aff03d369ab0456992e5/ 里 `train2id.txt`是三元文件，`entity2id.txt`和`relation2id.txt`是对应的实体和关系映射文件。

**Comment by zzg-971030** [comment]
感谢您提供的文件，我们在论文中会感谢您的开源精神！
